### ISSUE TITLE
How can i start a job?

### ISSUE THREAD

**Issue by andreanta** [AlariCode/nestjs-cron#1]
Hi, i'll try to use this module.
I have set up the example code, but no schedules is starting.
I have to register class in some place?
TIA
Andrea

**Comment by AlariCode** [comment]
First you need to register module in your root module:
``` javascript
import { CronModule } from 'nestjs-cron';

@Module({
	imports: [
		// ...
		CronModule.forRoot(),
	],
})
export class AppModule {}
```
Then decorate your class or service with decorator: `@Scheduled()` and method with `@Cron()`:
``` javascript
import { Cron, Scheduled } from 'nestjs-cron';

@Scheduled()
export class MyClass {
	@Cron('* * * * * *')
	async myMethod() {
		//...
	}
}
```
Remember to use `Scheduled` on class. Without it Cron will not work. `MyClass` can be a service or a controller and had to be included in some module in your app. That’s all you have to do. Can you show your code, that is not working?

**Comment by AlariCode** [comment]
@andreanta Your class has to be registered in module as a provider or a controller. 

May be it is not clear from documentation, so I’ll add some notes about it.

**Comment by AlariCode** [comment]
@andreanta I updated docs.

**Comment by andreanta** [comment]
Thanks, i have tried with simple class, 
now i tried with a service and works well .

Good work and thanks for support

**Comment by AlariCode** [comment]
@andreanta glad I can help)
